<template><div><h1 id="frequently-asked-questions" tabindex="-1"><a class="header-anchor" href="#frequently-asked-questions"><span>Frequently Asked Questions</span></a></h1>
<h2 id="are-your-ai-tools-really-free-to-use" tabindex="-1"><a class="header-anchor" href="#are-your-ai-tools-really-free-to-use"><span>Are your AI tools really free to use?</span></a></h2>
<p>Yes, all our AI utilities are completely free to use. We believe in making powerful AI tools accessible to everyone without any cost barriers.</p>
<h2 id="how-accurate-are-your-prediction-models" tabindex="-1"><a class="header-anchor" href="#how-accurate-are-your-prediction-models"><span>How accurate are your prediction models?</span></a></h2>
<p>Our models are continuously improving as we collect more data. While no prediction model can be 100% accurate, we strive to provide the most reliable insights possible based on the available data and our advanced algorithms.</p>
<h2 id="how-can-i-contribute-to-your-data-collection-efforts" tabindex="-1"><a class="header-anchor" href="#how-can-i-contribute-to-your-data-collection-efforts"><span>How can I contribute to your data collection efforts?</span></a></h2>
<p>You can participate in our data collection initiatives by following the links provided on our <a href="https://x.com/und3rd0gz" target="_blank" rel="noopener noreferrer">X account</a>. Your contributions help us improve our models and make better predictions for everyone. Learn more about <RouteLink to="/docs/features/community-contributions.html">community contributions</RouteLink>.</p>
<h2 id="when-will-the-meme-token-prediction-tool-be-fully-available" tabindex="-1"><a class="header-anchor" href="#when-will-the-meme-token-prediction-tool-be-fully-available"><span>When will the meme token prediction tool be fully available?</span></a></h2>
<p>Our <RouteLink to="/docs/products/meme-token-predictor.html">Meme Token Predictor</RouteLink>, which predicts meme token trends within the first 15 minutes of launch, is currently in the large-data collection and training phase. We're working hard to make it available as soon as possible. Follow our <a href="https://x.com/und3rd0gz" target="_blank" rel="noopener noreferrer">X</a> for the latest updates on its release.</p>
<h2 id="do-you-plan-to-add-more-prediction-tools-in-the-future" tabindex="-1"><a class="header-anchor" href="#do-you-plan-to-add-more-prediction-tools-in-the-future"><span>Do you plan to add more prediction tools in the future?</span></a></h2>
<p>Absolutely! We're starting with meme token predictions, but we have plans to expand into other areas where AI predictions can be valuable and entertaining. We're planning to develop a Cybersport Betting Assistant in the future, but it's still in the early planning phase. Check out our <RouteLink to="/docs/products/future-ai-tools.html">future AI tools</RouteLink> page for more information.</p>
<h2 id="how-does-your-early-trend-detection-work" tabindex="-1"><a class="header-anchor" href="#how-does-your-early-trend-detection-work"><span>How does your early trend detection work?</span></a></h2>
<p>Our <RouteLink to="/docs/features/early-trend-detection.html">early trend detection</RouteLink> system analyzes multiple data points in real-time, including initial trading volume, social media sentiment, wallet distribution, and historical patterns from similar tokens. By processing this data through our specialized algorithms, we can detect emerging trends much faster than manual analysis would allow.</p>
<h2 id="do-you-plan-to-support-cybersport-predictions-in-the-future" tabindex="-1"><a class="header-anchor" href="#do-you-plan-to-support-cybersport-predictions-in-the-future"><span>Do you plan to support cybersport predictions in the future?</span></a></h2>
<p>Yes, we're planning to develop a Cybersport Betting Assistant that will support predictions for popular esports titles including Counter-Strike (CS:GO/CS2), Dota 2, League of Legends, Valorant, and more. However, this project is still in the early planning phase and not yet in active development.</p>
<h2 id="how-do-you-analyze-social-sentiment" tabindex="-1"><a class="header-anchor" href="#how-do-you-analyze-social-sentiment"><span>How do you analyze social sentiment?</span></a></h2>
<p>Our <RouteLink to="/docs/features/social-sentiment-analysis.html">social sentiment analysis</RouteLink> system monitors and analyzes content from social media platforms, community forums, news outlets, and influencer activity. Using natural language processing and machine learning, we extract meaningful insights from this vast amount of unstructured data.</p>
<h2 id="how-can-i-get-notified-about-new-features-and-updates" tabindex="-1"><a class="header-anchor" href="#how-can-i-get-notified-about-new-features-and-updates"><span>How can I get notified about new features and updates?</span></a></h2>
<p>The best way to stay informed about our progress is to <a href="https://x.com/und3rd0gz" target="_blank" rel="noopener noreferrer">follow us on X</a>. We regularly share updates on our development progress, upcoming features, and opportunities to participate in beta testing.</p>
<h2 id="how-can-i-contact-your-team" tabindex="-1"><a class="header-anchor" href="#how-can-i-contact-your-team"><span>How can I contact your team?</span></a></h2>
<p>You can reach out to us through our <a href="https://x.com/und3rd0gz" target="_blank" rel="noopener noreferrer">X account</a> or via email at <a href="mailto:underd0gz.coop@gmail.com" target="_blank" rel="noopener noreferrer">underd0gz.coop@gmail.com</a>. For more information, visit our <RouteLink to="/docs/about/contact.html">contact page</RouteLink>.</p>
</div></template>


